[package]
name = "compiler"
version = "0.1.0"
edition = "2018"

[lib]
name = "compiler"
path = "src/lib.rs"

[[bin]]
name = "compiler-rin"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha = "*"
